airflow:
  image:
    repository: apache/airflow
    tag: 2.5.0
    pullPolicy: IfNotPresent
  executor: "LocalExecutor"
  # executor: CeleryExecutor
  # config:
  #   AIRFLOW__CORE__FERNET_KEY: "your-fernet-key"
  #   AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  #   AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
  # fernetKey: "your-fernet-key"
  web:
    service:
      type: LoadBalancer
    defaultUser:
      enabled: true
      username: admin
      password: admin1!
  config:
    AIRFLOW__CORE__FERNET_KEY: "myfernetkey"
    AIRFLOW__WEBSERVER__BASE_URL: "http://my-airflow-domain.com"

# git:
#   dags:
#     enabled: true
#     repositories:
#       - repository: "ssh://git@github.com/shevaleks/TZ.git"
#         name: "TEST_DAGS"
#         branch: "main"
#         path: ""
#         subPath: ""

dags:
  gitSync:
    enabled: true
    repo: git@github.com/shevaleks/TZ.git
    branch: main
    subPath: "/airflow/dags"
    sshKeySecret: airflow-ssh-secret
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: 'c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FDK3c1S1dkTFRGQkZLUm55d1RNN1pRTUdnWFhUNTZoQUNtSU9JOHI4Y2Zva2NjYW9Ma3lRa0p1VFVDV2lLUVFiT291emE4ZkZodkFVQi9BRVJ4Q2pFRHdJdjNadFFnaG9mNjIyL1dSdHYwWDJpRnNJcXRieFFpemtxS2FuSHByOHBXWkJ2b2Z2Y3RSb1hvUElqNGhzeUdpeURYb0ZMTmhna0RwYno1WmdQejUzVHpmWUprOUxRYVM3U0JNdDhCVWc4bkVlanlYemYwa2poVWo1bU1ieUM0OFZUQ01tUmN2N2ZLTnlMVDBRUkRMbnE5VkhpNGN3OVJYSUdRT3BWRlpVN3Bqa1dOT3JSbHY3TWpGc2haMEZzdFNndURoZUh3NVBPZzFrbDRpampheHVxeGhEUUExK3JMNEd6S3JFbnlWVDh4bDRXK01HejBCQ2JTamZMeFFUWVNWKzc1Ry9hcEF1YktiaWNUVHFRL3EvZkl0aEhkcUxvNTExME1WK3lzbFBPT2VuYXhWc3U3ak9wTTVjRVhXem1HUmY3dDNFaG5xQnJKU3VHUURMSGhDc3V5QmI4NlNMSitIU2k5cGxXQVpPa283cEwyU0IvQXFkZVhVTUM3TXlFc3dBbDBycEpZL2ZnWS93eUJEQmloTmlDRGRsejcxa05qT2E4WGVuZHVjVE09IHJvb3QxQE1hY0Jvb2stUHJvLUFsZWtzZXkubG9jYWw='