airflow:
  image:
    repository: apache/airflow
    tag: 2.5.0
    pullPolicy: IfNotPresent
  executor: "LocalExecutor"
  # executor: CeleryExecutor
  # config:
  #   AIRFLOW__CORE__FERNET_KEY: "your-fernet-key"
  #   AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  #   AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
  # fernetKey: "your-fernet-key"
  web:
    service:
      type: LoadBalancer
    defaultUser:
      enabled: true
      username: admin
      password: admin1!
  config:
    AIRFLOW__CORE__FERNET_KEY: "myfernetkey"
    AIRFLOW__WEBSERVER__BASE_URL: "http://my-airflow-domain.com"

git:
  dags:
    enabled: true
    repositories:
      - repository: "ssh://git@github.com/shevaleks/TZ.git"
        name: "TEST_DAGS"
        branch: "main"
        subPath: "airflow/dags"