apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    app: {{ include "airflow.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "airflow.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "airflow.name" . }}
    spec:
      containers:
        - name: airflow
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: AIRFLOW__WEBSERVER__RBAC
              value: "false"
            # Add other Airflow environment variables as needed
