apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-web
  labels:
    app: {{ include "airflow.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.airflow.web.service.type }}
  ports:
    - port: {{ .Values.airflow.web.service.port }}
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app: {{ include "airflow.name" . }}
