airflow:
  # image:
  #   repository: apache/airflow
  #   tag: 2.5.0
  #   pullPolicy: IfNotPresent
  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.9.2-debian-12-r1
  web:
    enabled: true
    containerPorts:
      http: 8080
    service:
      type: ClusterIP
      port: 8080
      externalPort: 80
    defaultUser:
      enabled: true
      username: admin
      password: admin1!

workers:
  ## if the airflow workers StatefulSet should be deployed
  enabled: true

  ## the number of worker Pods to run
  replicas: 1

extraEnv:
  - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
    value: "airflow.utils.net.get_host_ip_address"
